### ISSUE TITLE
Not working on Fedora 29

### ISSUE THREAD

**Issue by oldfellla** [trizen/menutray#15]
After upgrade my laptop from Fedora 28 to 29 Menutray does not work any more.
Error message is:

Can't load '/home/user/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Glib/Glib.so' for module Glib: libperl.so.5.26: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 193.
 at /usr/lib64/perl5/vendor_perl/Gtk2.pm line 30.
Compilation failed in require at /usr/lib64/perl5/vendor_perl/Gtk2.pm line 30.                                                                     
BEGIN failed--compilation aborted at /usr/lib64/perl5/vendor_perl/Gtk2.pm line 30.                                                                 
Compilation failed in require at /home/user/.config/menutray/menu.pl line 11.                                                                      
BEGIN failed--compilation aborted at /home/user/.config/menutray/menu.pl line 11.  

Fedora 29 updated to libperl.so.5.28 and simply linking it to libperl.so.5.26 does not work.
Any idea?

**Comment by trizen** [comment]
You have to rebuild the [Gtk2](https://metacpan.org/pod/Gtk2) Perl module (or at least the [Glib](https://metacpan.org/pod/Glib) module) (`cpanm --reinstall Gtk2 Glib`), or install them from the official repos and remove them from `~/perl5/lib`.

See: https://pkgs.org/download/perl(Gtk2)

**Comment by oldfellla** [comment]
Thanks, it took 1 minute and it worked, excellent!
By the way, it is an awesomely useful nice app, many thanks for making it

**Comment by trizen** [comment]
No problem. I am glad that you find menutray useful. :)
